#!/bin/sh

bluetoothctl power on

cat <<EOF | bluetoothctl
agent on
discoverable on
agent NoInputNoOutput
default-agent
EOF


remove_connections() {
	# killing all current connections
	for dev in $(bluetoothctl devices | cut -d ' ' -f 2); do
		echo "removing $dev"
		bluetoothctl disconnect "$dev"
		bluetoothctl remove "$dev"
	done
}


step() {
	remove_connections

	count=3
	i=1
	while [ $i -le $count ]; do
		echo "$i/$count"
		python test.py
		i=$((i + 1))
	done
}

while true; do
	step
done
